### ISSUE TITLE
Mantle Incompatability: Health Increases

### ISSUE THREAD

**Issue by IdrisQe** [LocusWay/OverpoweredArmorBar#7]
In version 0.3.0, gaining more health bars with Mantle installed causes hearts to recolor in a similar way to the armor bar rather than adding more bars of hearts. The armor bar raises to accommodate new heart bars that aren't there with this mod installed as of the latest update

Of note: Even with Mantle, having the Absorption effect will still add a second bar of hearts.

**Comment by LocusWay** [comment]
At the moment I don't support the use of this mod with other mods that adjust the health bar.
This is because there are a number of ways mods could change the health bar and it would be difficult for me to tell what they are doing without knowing what other mods are doing and knowing their current settings.
